### ISSUE TITLE
icssync distinguishes Wifi from non Wifi

### ISSUE THREAD

**Issue by dontcallmedom** [w3c-webmob/netinfo-usecases#25]
![ICSSync app screenshot](https://f.cloud.github.com/assets/216410/1733506/f5967794-6338-11e3-9faa-54556a530419.png)

**Comment by marcoscaceres** [comment]
@dontcallmedom are this the default sync options for "ice cream sandwich"? Can you provide a sentence describing the option and I can add it to the doc?

**Comment by marcoscaceres** [comment]
@dontcallmedom ping.

**Comment by dontcallmedom** [comment]
oops, sorry for the lag; yes, these are the options for Ice Cream Sandwich. The option enables the user to determine whether the synchronization with on-line icalendars should happen whenever the user is connected, or only when connected on wifi.

**Comment by marcoscaceres** [comment]
So, I think I'm going to exclude this one as I want to stick to the latest versions of each OS. Hope that is ok.

**Comment by dontcallmedom** [comment]
I think there is some confusion (and likewise for issue #29): ICSSync and Caldav-sync are applications, not configuration of the operating system; as such, I assume they're behave the same in 4.4 as they do in 4.x.

**Comment by marcoscaceres** [comment]
Ah, sorry! Hurray for badly named apps! :D
