### ISSUE TITLE
Economist app distinguishes 3G, Wifi (but not clear how)

### ISSUE THREAD

**Issue by dontcallmedom** [w3c-webmob/netinfo-usecases#26]

**Comment by dontcallmedom** [comment]
![Download settings for The Economist app](https://f.cloud.github.com/assets/216410/1733533/79621c0e-6339-11e3-8ee5-1ad48e61d93a.png)

**Comment by marcoscaceres** [comment]
It's interesting that this option also shows up in the nexus 7 (which is not a cellular enabled device, AFAIK).
