### ISSUE TITLE
Add information about network information use cases for Mozilla's carrier billing payments

### ISSUE THREAD

**Issue by ernesto-jimenez** [w3c-webmob/netinfo-usecases#27]
Mozilla marketplace payments authentication for carrier billing changes depending on whether the user is on WiFi or cellular.

@kumar303 can provide some details and screenshots.

**Comment by kumar303** [comment]
I'll try to get a screenshot for a pull request but while it's fresh on my mind, this is the use case:

For a first time [payment on Firefox OS](https://developer.mozilla.org/en-US/Marketplace/Monetization/In-app_payments?redirectlocale=en-US&redirectslug=Mozilla%2FMarketplace%2FIn-app_payments) using [Bango](http://web.bango.net/) one of two things may happen:
1. If the user is on a network connection (3g, 4g, etc) then Bango will attempt to make an HTTP request to a special operator service which can sniff operator-injected headers to authenticate the user. When successful, direct billing is set up immediately.
2. If the user is on WiFi then Bango needs to do an SMS challenge to authenticate the user's phone for direct billing. This is more cumbersome and error prone. The user must wait for a PIN code, find it in their SMS application, then enter it into the web form before the payment can begin.

**Comment by ernesto-jimenez** [comment]
Thanks Kumar!

It would also be nice to have your feedback on wether a netinfo API could be useful to cover such use case.

**Comment by marcoscaceres** [comment]
@kumar303, sorry to bother, but could you possibly drop in the screenshot? Be good to get the above into the document.

**Comment by kumar303** [comment]
Sure, here are a couple.

Beginning an SMS / PIN authentication for direct billing:

![2014-01-08-10-31-46](https://f.cloud.github.com/assets/55398/1870244/d5961556-7884-11e3-8144-d103d6c5b0f8.png)

Entering a PIN after receiving the SMS:

![2014-01-08-10-32-48](https://f.cloud.github.com/assets/55398/1870247/e2a0b2a6-7884-11e3-8778-10fd8a194b2d.png)

When successfully authenticated (or after doing silent SMS) you can put charges on your bill:

![2014-01-08-10-43-19](https://f.cloud.github.com/assets/55398/1870259/ff0b02de-7884-11e3-836b-afb1403c5f8d.png)

**Comment by marcoscaceres** [comment]
@ernesto-jimenez, as you know the inner workings of this stuff, could you please compile this into a PR?
