### ISSUE TITLE
Android Caldav-sync settings

### ISSUE THREAD

**Issue by dontcallmedom** [w3c-webmob/netinfo-usecases#29]
This one lists all the possible type of networks that Android exposes; worth noting: it also allows to override the background-data setting of Android.
![Data Service Settings in Android CalDav-sync](https://f.cloud.github.com/assets/216410/1734088/a0798216-6341-11e3-9b63-106e3c36f46b.png)

**Comment by marcoscaceres** [comment]
Nice find!

**Comment by marcoscaceres** [comment]
@dontcallmedom, I've not been able to find this in Android 4.4. Any idea where I might look?

**Comment by dontcallmedom** [comment]
As alluded in #25, this is an app, not an android setting.
