### ISSUE TITLE
Requirements derived from use cases seem to specific

### ISSUE THREAD

**Issue by dontcallmedom** [w3c-webmob/netinfo-usecases#33]
While the proposed requirements derived from the high level use cases would probably help fulfill the use cases, it's arguable that these are the only requirements that would fulfill them.
For instance, a "download manager" system might work better for the "large download" use case, instead of letting developers manage this via connection-type detection.
In particular, when doing the derivation, one ought to ask whether replicating the native use cases ought to be done by the app directly, or through some mediation via the browser.

**Comment by marcoscaceres** [comment]
I think we need to add the above to the discussion section. I think we are getting to the point where we can start having a fairly informed discussion about what we have found. 

I'm wondering how many more apps we should try to find before we start the discussion...

**Comment by marcoscaceres** [comment]
Just some thoughts:
- the downloads are very application specific... so, while a the download manager would probably do the trick, the download process still needs to provide feedback (progress and errors) to the application irrespective of connection type. I don't know of current d/l managers can do this. 
- General system wide options for downloads may apply... though size of downloads might not be known ahead of time.
- Setting global options might be annoying for users - as overriding options for one application might override it for all. For example, I sometimes want to be able to d/l audiobooks on cellular (cost/quota be damned!) but I don't want to accidentally kick off a bunch of other sync...this is my fear with tethering: when I tether with my iPhone to quickly check something online, I need to make sure that Dropbox doesn't suddenly start d/l and uploading like crazy! It's done that to me before. The same can happen with other services - basically any app that receives a network event, like email apps, iCloud, etc.
