### ISSUE TITLE
Integrate developer feedback

### ISSUE THREAD

**Issue by marcoscaceres** [w3c-webmob/netinfo-usecases#5]
Integrate the good stuff from:
http://oksoclap.com/p/netinfo_usecases

**Comment by nrooney** [comment]
Do we think these are covered by the ones already on here? 

We're looking into
- prevent low bandwidth users from even starting a video stream
- increase request-timeouts to account for higher latency
- artificially slow down the experience (slower transitions) to ease the pain of lower bandwidth
- possibly prevent analytics tools from adding to the pain
- fall back to low-res or even no images where possible

**Comment by marcoscaceres** [comment]
> - prevent low bandwidth users from even starting a video stream

That should never happen. Bandwidth is variable. 

> - increase request-timeouts to account for higher latency

This seems like over-engineering. 

> - artificially slow down the experience (slower transitions) to ease the pain of lower bandwidth

This seems kinda like a nice to have, but seems like a recipe for disaster. Again, the problem is that bandwidth is highly variable. 

> -  possibly prevent analytics tools from adding to the pain

These are handled at a different level... e.g., using defer or lazyload. 

>    fall back to low-res or even no images where possible

See: 
http://lists.w3.org/Archives/Public/public-web-perf/2013Dec/0072.html

**Comment by marcoscaceres** [comment]
closed via 4d9917b0e818a38b8c9a61ed20c91f9b0745fd85
