### ISSUE TITLE
Tizen uses network type in a DownloadManager interface

### ISSUE THREAD

**Issue by dontcallmedom** [w3c-webmob/netinfo-usecases#61]
I just happened to notice the following bits in the Tizen API:
https://developer.tizen.org/dev-guide/2.2.1/org.tizen.web.device.apireference/tizen/download.html#::Download::DownloadNetworkType

From what I understand, this lets app download content in the background, while specifying on what type of network that download should be done. Would be nice if we can integrate that piece in the document (but I won't have the bandwidth to submit a pull request before a while I'm afraid)

**Comment by marcoscaceres** [comment]
@anssiko can maybe help?

**Comment by marcoscaceres** [comment]
I'll try to add the above to the discussion section.

**Comment by anssiko** [comment]
@dontcallmedom @marcoscaceres The API is essentially a download manager, as described in the "Managing downloads" section of the doc. I added some text in PR https://github.com/w3c-webmob/netinfo/pull/62
