### ISSUE TITLE
Mixed content makes this un-viewable in Firefox

### ISSUE THREAD

**Issue by domenic** [w3c-webmob/netinfo-usecases#67]
https://w3c-webmob.github.io/netinfo-usecases/ is no good

**Comment by marcoscaceres** [comment]
Oops! How embarrassing! Should be all good now.

**Comment by Gug-cpu** [comment]
[Zero_Trust_for_SaaS_Apps_Solution_Brief.pdf](https://github.com/user-attachments/files/22060647/Zero_Trust_for_SaaS_Apps_Solution_Brief.pdf)
